---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-frontend
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    app.kubernetes.io/name: hello-world-frontend
spec:
  selector:
    app: hello-world-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
