---
apiVersion: v1
kind: Service
metadata:
  name: whoami-frontend
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: whoami-frontend
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: whoami-frontend
    task: whoami-frontend
  # type: ClusterIP